### ISSUE TITLE
Properly define possible errno results

### ISSUE THREAD

**Issue by ritave** [WebAssembly/WASI#215] opened 2020-01-29 13:50 UTC
Currently, the possible results of sys calls returning errno are an undefined behaviour.

For example, let's get [args get](https://github.com/WebAssembly/WASI/blob/master/phases/ephemeral/docs.md#-getargv-pointerpointerchar8-argv_buf-pointerchar8---errno). What should be the effect if the pointer is out of bounds, should it trap the execution, or return errno? If it should return errno, which one?
What other errno's can occur resulting from args.get function and when?

**Comment by pchickey** [comment] 2020-01-29 20:37
This is a good line of inquiry and we could make some significant improvements to WASI's representation of errors.

WASI interfaces should never trap, except for functions marked `noreturn`, which should always terminate execution, whether through trapping or some other runtime-provided mechanism. When passed an out-of-bounds pointer, implementations currently use `errno.inval` to indicate that the argument was invalid.

I don't think WASI's current use of the posix-styl eall-errors-in-one-enum `errno` is the design we should stick with forever. Most (maybe all) functions should only ever return a small subset of the variants in errno. One way to start figuring out a better design would be to audit each function and enumerate all the variants it can reasonably return. Once we have that, we can start defining new specialized error enums that work for smaller families of functions, switching the family from errno to the new enum in ephemeral. The wasi-libc implementation would still need to convert these specialized enums back into an errno, but other guest and host-side implementations of the WASI interfaces would benefit.

**Comment by bjorn3** [comment] 2020-01-29 21:07
For syscalls like `open` it would be possible to for example return EHOSTDOWN when the file is stored on a different machine and accessed using some network file system, or just because somebody decided to (ab)use fuse. It could also return any other error code.

**Comment by linclark** [comment] 2021-03-17 18:03
Thanks for filing this. As Pat speculated above, we decided against having the "all-errors-in-one-enum errno".

Once WASI modularization is complete, we'll be [refactoring the errors](https://github.com/WebAssembly/WASI/projects/1) so that each module only contains the errors that are relevant to its functions. In the later stages of that process, we will be auditing each function to enumerate all the variants it can reasonably return. 

That work is taking place in various proposal repos and being tracked in the project linked above, so I'm going to close this one out.

**Closed by linclark** 2021-03-17 18:03 UTC

**Comment by codefromthecrypt** [comment] 2022-02-16 23:23
Is it required to delay definition of errors until post modularization? Currently implementations use different codes due to this not being addressed for nearly a year. This means they are not compatible in material ways as well cause implementation delays as people fumble around wondering which codes to use.

**Comment by sunfishcode** [comment] 2022-02-16 23:38
It isn't strictly required to wait for modularization, but modularization isn't the only thing happening here, there's also the transition to the new wit-based tooling, along with the new interface-types support.

For `random_get` specifically, I'm expecting to propose that it never return any errors, so that we don't end up with applications having fallback paths for the case where it fails, which are historically error-prone.

**Comment by programmerjake** [comment] 2022-02-17 00:02
> For `random_get` specifically, I'm expecting to propose that it never return any errors, so that we don't end up with applications having fallback paths for the case where it fails, which are historically error-prone.

that is a problem for those who specifically want 100% deterministic execution, part of that is that `random_get` can't return random results (because those aren't repeatable), so essentially the only reasonable option is to return an error.

**Comment by sunfishcode** [comment] 2022-02-17 00:07
Environments which require 100% deterministic execution should ideally not provide the `random_get` export, so that applications that attempt to import it fail at link time rather than at runtime.

**Comment by programmerjake** [comment] 2022-02-17 01:01
> Environments which require 100% deterministic execution should ideally not provide the `random_get` export, so that applications that attempt to import it fail at link time rather than at runtime.

ah, yeah, that likely works better

**Comment by codefromthecrypt** [comment] 2022-02-17 03:00
Just to clarify the problem is more general than nuance of random source. For example, a great start would be defining code one should use when pointers for result params are invalid (ex. argc is out of range of the underlying memory). Maybe with that carved out, we can proceed one-by-one with functions?

**Comment by sunfishcode** [comment] 2022-02-18 21:16
For the most part, WASI in its current form falls back on POSIX-like conventions. POSIX would likely use `EINVAL` for a situation where a pointer or length is invalid, so that makes sense for WASI's current argv/argc conventions.

The broader situation with the argv/argc functions is that we haven't put much effort into polishing the details, because we've been preparing to redesign them entirely when we have the new interface types tooling underneath us. If anyone is interested in working on error codes, the filesystem functions might be a good place to start. The spec is [here](https://github.com/WebAssembly/wasi-filesystem/blob/main/wasi-filesystem.wit.md), and already converted to the new wit format, and it's ready to accept PRs.
